#!/usr/bin/env sh

# Function to handle errors
handle_error() {
  echo "Error: $1"
  exit 1
}

echo "executing post-commit hook..."

message="$(git log -1 --pretty=%B)"
echo last commit message: $message
cp src/coupon/* web-components
cd web-components

echo "commiting submodule..."
# env -i git status || handle_error "Failed to get git status"
env -i git add -A  || handle_error "Failed to add"
env -i git commit -m "update from master: $message"  || handle_error "Failed to commit"
# git push origin components

echo "post-commit hook complete!"