#!/usr/bin/env sh

# Function to handle errors
handle_error() {
  echo "Error: $1"
  exit 1
}

echo "executing pre-push hook..."

cd web-components

echo "pushing submodule..."
# env -i git status || handle_error "Failed to get git status"
# env -i git add -A 
# env -i git commit -m "update from master: $message" 
env -i git push origin components

echo "pre-push hook complete!"